### ISSUE TITLE
can't load account?

### ISSUE THREAD

**Issue by fauno** [asn-the-goblin-slayer/flute#6] opened 2016-05-15 04:27 UTC
this happened after pulling latest changes, but resetting to b3867d3b8cff1c38fbbfc1de0c1ab447dc51de27 throws the same error. i removed the privkey file and it fails the same

```
python: cargando el script "/home/fauno/.config/weechat/python/weechat_viola.py"
python: stdout/stderr: !!! Failed to import PyNaCl: 'Could not initialize sodium 1'
python: stdout/stderr: !!! Might be caused by https://github.com/pyca/pynacl/issues/186
python: stdout/stderr: !!! Ignoring error, but no guarantees that viola will work... :(
python: script "viola" registrado, versión 0.0.1 (One always plays the viola while they drink and chatter...)
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/fauno/.config/weechat/python/weechat_viola.py", line 133, in <module>
python: stdout/stderr:     accounts.init_accounts(viola_dir)
python: stdout/stderr:   File "/home/fauno/.config/weechat/python/viola/accounts.py", line 15, in init_accounts
python: stdout/stderr:     ACCOUNT = Account(viola_dir)
python: stdout/stderr:   File "/home/fauno/.config/weechat/python/viola/accounts.py", line 38, in __init__
python: stdout/stderr:     self.init_crypto()
python: stdout/stderr:   File "/home/fauno/.config/weechat/python/viola/accounts.py", line 59, in init_crypto
python: stdout/stderr:     self.identity_privkey = crypto.load_identity_privkey_from_disk(self.identity_privkey_fname)
python: stdout/stderr:   File "/home/fauno/.config/weechat/python/viola/crypto.py", line 44, in load_identity_privkey_from_disk
python: stdout/stderr:     return nacl.signing.SigningKey(binascii.unhexlify(hexed_privkey))
python: stdout/stderr: AttributeError: 'module' object has no attribute 'signing'
python: no es posible analizar el archivo "/home/fauno/.config/weechat/python/weechat_viola.py"
python: no es posible ejecutar la función "debug_buffer_close_cb"
python: no es posible ejecutar la función "debug_buffer_close_cb"
```

**Comment by fauno** [comment] 2016-05-15 04:33
sorry, without priv_key the error is slightly different. my guess was that removing the privkey it would generate a new one

```
python: cargando el script "/home/fauno/.config/weechat/python/weechat_viola.py"
python: stdout/stderr: !!! Failed to import PyNaCl: 'Could not initialize sodium 1'
python: stdout/stderr: !!! Might be caused by https://github.com/pyca/pynacl/issues/186
python: stdout/stderr: !!! Ignoring error, but no guarantees that viola will work... :(
python: script "viola" registrado, versión 0.0.1 (One always plays the viola while they drink and
 chatter...)
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/fauno/.config/weechat/python/weechat_viola.py", line 133, in
 <module>
python: stdout/stderr:     accounts.init_accounts(viola_dir)
python: stdout/stderr:   File "/home/fauno/.config/weechat/python/viola/accounts.py", line 15, in
 init_accounts
python: stdout/stderr:     ACCOUNT = Account(viola_dir)
python: stdout/stderr:   File "/home/fauno/.config/weechat/python/viola/accounts.py", line 38, in
 __init__
python: stdout/stderr:     self.init_crypto()
python: stdout/stderr:   File "/home/fauno/.config/weechat/python/viola/accounts.py", line 61, in
 init_crypto
python: stdout/stderr:     self.identity_privkey = crypto.gen_signing_privkey()
python: stdout/stderr:   File "/home/fauno/.config/weechat/python/viola/crypto.py", line 32, in g
en_signing_privkey
python: stdout/stderr:     return nacl.signing.SigningKey.generate()
python: stdout/stderr: AttributeError: 'module' object has no attribute 'signing'
python: no es posible analizar el archivo "/home/fauno/.config/weechat/python/weechat_viola.py"
python: no es posible ejecutar la función "debug_buffer_close_cb"
python: no es posible ejecutar la función "debug_buffer_close_cb"
```

**Comment by asn-d6** [comment] 2016-05-15 05:06
Hello there! Hmm, seems like b3867d3 was not sufficient to solve the problem! Something seems to initializing libsodium twice there, and I'm not quite sure what! I can't reproduce this problem in my system :/

Can you let me know some more info about your setup that might help debug this? Specifically, what weechat version? What python version? What PyNaCl version? Anything else weird on your setup? Do you call the `/script load weechat_viola.py` command twice or something? :(

Until I manage to fix this problem, the only thing I can recommend is to manually patch PyNaCl using this patch: https://github.com/pyca/pynacl/commit/289e3c83c42e72b5d44422b1a48d7c573b90d3f4
It shouldn't be too hard to do so, but it sucks and I will try to find a fix for this ASAP.

peace

**Comment by fauno** [comment] 2016-05-15 14:34
versions:
- weechat 1.5
- python 2.7.11
- pynacl 1.0.1 (installed using pip)

i'm loading it with `/python load python/weechat_viola.py`, and since it
fails to load, i can't unload it, so i run the `/python` line again.

i'll try with another weechat session too see how it goes

## 

 D

**Comment by fauno** [comment] 2016-05-15 14:42
from another machine with weechat 1.4 it loaded on the first try and it does throw the initialization error when i try to load it twice or just reload it.  after the failed reload, weechat assumes the script isn't loaded but i can reproduce the initialization error

**Comment by asn-d6** [comment] 2016-05-15 19:09
Yes, if you load it twice, it does make sense that you get this error. Because the first time you load it, pynacl initializes sodium, and then the second time it's already initialized so https://github.com/pyca/pynacl/issues/186 triggers. This problem will fixed when pynacl fixes the bug.

For now I'm more interested in the case where loading viola a single time fails. I need to look deeper into this.

**Comment by fauno** [comment] 2016-05-15 20:31
i think the other fails were because i was already loading viola and
getting the other errors i reported.  weechat was never restarted.

it seems odd to me that sodium keeps being initialized by weechat when
the script isn't loaded though

**Comment by asn-d6** [comment] 2016-05-16 01:23
Yes, I also don't understand how this is happening :(

One way to debug it would be to have PyNaCl log a stacktrace into a file everytime it does a `sodium_init()`. Then you could check the file to see what calls the first `sodium_init()`. Here is a pynacl patch for doing this in case you want to try it out:

```

From 8b19d463801330d6d7012184306fc7f8a914d658 Mon Sep 17 00:00:00 2001
From: George Kadianakis <desnacked@riseup.net>
Date: Sun, 15 May 2016 21:20:54 -0400
Subject: [PATCH] log into file

---
 src/nacl/bindings/sodium_core.py | 13 +++++++++++--
 1 file changed, 11 insertions(+), 2 deletions(-)

diff --git a/src/nacl/bindings/sodium_core.py b/src/nacl/bindings/sodium_core.py
index ec6d7fa..7422798 100644
--- a/src/nacl/bindings/sodium_core.py
+++ b/src/nacl/bindings/sodium_core.py
@@ -16,11 +16,20 @@ from __future__ import absolute_import, division, print_function
 from nacl._sodium import lib
 from nacl.exceptions import CryptoError

+import traceback
+import time

 def sodium_init():
     """
     Initializes sodium, picking the best implementations available for this
     machine.
     """
-    if lib.sodium_init() == -1:
-        raise CryptoError("Could not initialize sodium")
+    f = open("/tmp/viola.log", "a")
+    f.write("[%s] Hello machine:\n" % str(time.time()))
+    f.write(str(traceback.print_stack(file=f)))
+    f.write("-\n"*40)
+    f.close()
+
+    retval = lib.sodium_init()
+    if retval != 0:
+        raise CryptoError("Could not initialize sodium %d" % retval)
-- 
2.1.4
```

**Comment by asn-d6** [comment] 2016-05-26 00:47
Closing this as a dup of https://github.com/asn-the-goblin-slayer/flute/issues/2 .

**Closed as completed by asn-d6** 2016-05-26 00:47 UTC
